name: Build and Deploy React App

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow writing to repository contents

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and cache dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app using Vite
      - name: Build the app
        run: npm run build

      # Step 5: Deploy to GitHub Pages (ensure deploy to gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_dir: ./dist  # Path to the build output directory
          branch: gh-pages    # Push to gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token or a custom PAT if needed
